version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"
    depends_on:
      - api1
      - api2

  api1: &api
    image: lucasilverio/rinha-backend-2025:v1
    hostname: api1
    environment:
      - SERVER_PORT=8080
      - SPRING_REDIS_HOST=redis
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "300MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - INSTANCE_ID=API-2

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true